CREATE DATABASE IF NOT EXISTS EmployeeDB;
USE EmployeeDB;

DROP TABLE IF EXISTS Employee;
CREATE TABLE Employee (
  empid BIGINT NOT NULL AUTO_INCREMENT,
  emp_name VARCHAR(50) DEFAULT NULL,
  emp_salary FLOAT DEFAULT NULL,
  emp_age INTEGER DEFAULT NULL,
  emp_city VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (empid)
);

USE EmployeeDB;
SELECT * FROM Employee;